#!/usr/bin/env python3
"""
Telegram Bot with AWS Bedrock Integration and Kiro CLI

Supports two modes:
- /chat: Send prompts to Bedrock (default)
- /code: Send prompts to Kiro CLI
- /help: Show available commands

Requires: TELEGRAM_API_KEY, TELEGRAM_CHAT_ID
Optional:  AWS_REGION, KIRO_OUTPUT_DIR, S3_BUCKET_NAME, S3_PREFIX,
           CLOUDFRONT_BASE_URL
"""

import json
import logging
import os
import re
import subprocess
import sys
import time
from pathlib import Path

import boto3
import requests

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

try:
    from dotenv import load_dotenv
    env_file = Path(__file__).parent / '.env'
    if env_file.exists():
        load_dotenv()
        logging.info(f"Loaded configuration from {env_file}")
    else:
        logging.info("No .env file found, using environment variables for configuration")
except ImportError:
    logging.warning("python-dotenv not installed, using environment variables for configuration")

# Path to the Kiro steering file that tells Kiro where to save outputs
KIRO_STEERING_FILE = Path(__file__).parent / ".kiro" / "steering" / "output-config.md"


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

def redact_key(value):
    """Redact middle portion of API keys, keeping first 4 and last 4 characters."""
    if not value or len(value) <= 8:
        return value
    return f"{value[:4]}...{value[-4:]}"


def get_config():
    api_key = os.environ.get('TELEGRAM_API_KEY')
    chat_id = os.environ.get('TELEGRAM_CHAT_ID')
    region = os.environ.get('AWS_REGION', 'us-west-2')
    kiro_output_dir = os.environ.get('KIRO_OUTPUT_DIR', '').strip()
    cloudfront_base_url = os.environ.get('CLOUDFRONT_BASE_URL', '').rstrip('/')
    s3_prefix = os.environ.get('S3_PREFIX', '').strip('/')

    logging.info("Environment variables loaded:")
    logging.info(f"  TELEGRAM_API_KEY: {redact_key(api_key)}")
    logging.info(f"  TELEGRAM_CHAT_ID: {chat_id}")
    logging.info(f"  AWS_REGION: {region}")
    logging.info(f"  KIRO_OUTPUT_DIR: {kiro_output_dir}")
    logging.info(f"  CLOUDFRONT_BASE_URL: {cloudfront_base_url}")
    logging.info(f"  S3_PREFIX: {s3_prefix}")

    if not api_key or not chat_id:
        print("Error: TELEGRAM_API_KEY and TELEGRAM_CHAT_ID must be set")
        sys.exit(1)

    return api_key, chat_id, region, kiro_output_dir, cloudfront_base_url, s3_prefix


# ---------------------------------------------------------------------------
# Kiro output directory and context file
# ---------------------------------------------------------------------------

def ensure_output_dir(kiro_output_dir):
    """Create the Kiro output directory if it does not exist."""
    if not kiro_output_dir:
        return
    path = Path(kiro_output_dir)
    path.mkdir(parents=True, exist_ok=True)
    print(f"Kiro output directory: {path.resolve()}")


def generate_kiro_context(kiro_output_dir, cloudfront_base_url="", s3_prefix=""):
    """Write (or overwrite) the Kiro steering file with the current output path.

    The file lives at .kiro/steering/output-config.md and is automatically
    picked up by Kiro CLI on every invocation so it always knows where to
    save generated files.
    """
    if not kiro_output_dir:
        return

    KIRO_STEERING_FILE.parent.mkdir(parents=True, exist_ok=True)
    
    # Build URL instruction if CloudFront is configured
    url_instruction = ""
    if cloudfront_base_url:
        if s3_prefix:
            url_pattern = f"{cloudfront_base_url}/{s3_prefix}/$FILENAME"
        else:
            url_pattern = f"{cloudfront_base_url}/$FILENAME"
        
        url_instruction = f"""
## File Access URLs

After saving a file, inform the user that it can be accessed at:

**URL Pattern:** `{url_pattern}`

Replace `$FILENAME` with the actual filename (including any subdirectories relative to the output directory).

**Example:**
- If you save `report.html`, the URL is: `{cloudfront_base_url}/{s3_prefix + '/' if s3_prefix else ''}report.html`
- If you save `data/analysis.csv`, the URL is: `{cloudfront_base_url}/{s3_prefix + '/' if s3_prefix else ''}data/analysis.csv`
"""
    
    content = f"""# Kiro CLI Output Configuration

> **Note:** This file is automatically regenerated by `telegram_bot.py` on
> every startup from the `KIRO_OUTPUT_DIR` environment variable. Manual edits
> will be overwritten. To change the output directory, update `KIRO_OUTPUT_DIR`
> in your `.env` file and restart the bot.

## File Output Location

When saving files, outputs, reports, code, or any other generated content,
**always save them to the configured output directory** shown below.

**Output Directory:** `{kiro_output_dir}`
{url_instruction}
## Naming Conventions

- Use lowercase filenames with hyphens as word separators (e.g., `my-report.html`)
- Include a date suffix for time-sensitive outputs (e.g., `summary-2024-01-15.md`)
- Use the appropriate file extension for the content type

## Guidelines

- Save all generated HTML, Markdown, JSON, CSV, and other output files to the
  output directory above.
- Create subdirectories within the output directory when organising related files
  (e.g., `images/`, `data/`, `reports/`).
- Do **not** save temporary or intermediate working files to the output directory.
- After completing a task, confirm which files were saved and their filenames so
  the bot can report the correct URLs.
"""
    KIRO_STEERING_FILE.write_text(content, encoding="utf-8")
    print(f"Kiro context file updated: {KIRO_STEERING_FILE}")


# ---------------------------------------------------------------------------
# File detection helpers
# ---------------------------------------------------------------------------

def snapshot_dir(directory):
    """Return a dict mapping file paths to their modification times."""
    result = {}
    if not directory:
        return result
    base = Path(directory)
    if not base.exists():
        return result
    for f in base.rglob("*"):
        if f.is_file():
            try:
                result[str(f)] = f.stat().st_mtime
            except OSError:
                pass
    return result


def new_files_since(before, after):
    """Return paths that are new or have been modified between two snapshots."""
    changed = []
    for path, mtime in after.items():
        if path not in before or before[path] != mtime:
            changed.append(path)
    return changed


def build_url(file_path, kiro_output_dir, cloudfront_base_url, s3_prefix):
    """Build the CloudFront URL for a file that lives inside kiro_output_dir."""
    if not cloudfront_base_url:
        return None
    try:
        rel = Path(file_path).relative_to(kiro_output_dir)
    except ValueError:
        return None
    parts = [cloudfront_base_url]
    if s3_prefix:
        parts.append(s3_prefix)
    parts.append(str(rel))
    return "/".join(parts)


# ---------------------------------------------------------------------------
# Telegram helpers
# ---------------------------------------------------------------------------

def strip_ansi(text):
    return re.sub(r'\x1b\[[0-9;?]*[a-zA-Z]', '', text)


def send_message(api_key, chat_id, text):
    try:
        requests.post(
            f"https://api.telegram.org/bot{api_key}/sendMessage",
            json={"chat_id": chat_id, "text": strip_ansi(text)},
            timeout=10
        )
    except Exception as e:
        print(f"Failed to send message: {e}")


def check_monitor_status():
    """Check if the folder monitor process is running."""
    pid_file = Path(__file__).parent / "log" / "folder_monitor.pid"
    
    if not pid_file.exists():
        return "❌ Folder monitor is not running\n\nStart it with: ./run_monitor.sh"
    
    try:
        pid = int(pid_file.read_text().strip())
        # Check if process is running
        try:
            os.kill(pid, 0)  # Signal 0 checks if process exists
            kiro_output_dir = os.environ.get('KIRO_OUTPUT_DIR', 'kirobot-out')
            return f"✅ Folder monitor is running\n\nPID: {pid}\nWatching: {kiro_output_dir}"
        except OSError:
            return f"❌ Folder monitor is not running\n\nStale PID file found (PID {pid} not active)\nStart it with: ./run_monitor.sh"
    except (ValueError, OSError) as e:
        return f"❌ Error checking monitor status: {e}"


# ---------------------------------------------------------------------------
# Backend invocations
# ---------------------------------------------------------------------------

def invoke_bedrock(bedrock, prompt):
    try:
        response = bedrock.invoke_model(
            modelId="global.anthropic.claude-sonnet-4-5-20250929-v1:0",
            body=json.dumps({
                "anthropic_version": "bedrock-2023-05-31",
                "max_tokens": 4096,
                "messages": [{"role": "user", "content": prompt}]
            })
        )
        result = json.loads(response['body'].read())
        return result['content'][0]['text']
    except Exception as e:
        return f"Error: {e}"


def invoke_kiro(prompt, kiro_output_dir, cloudfront_base_url, s3_prefix):
    """Run kiro-cli and detect any files it creates in kiro_output_dir.

    Returns (output_text, list_of_(filename, url) tuples).
    """
    before = snapshot_dir(kiro_output_dir)

    try:
        result = subprocess.run(
            ["kiro-cli", "chat", "--no-interactive", prompt],
            capture_output=True,
            text=True,
            timeout=300
        )
        output = result.stdout if result.stdout else result.stderr
    except Exception as e:
        return f"Error: {e}", []

    after = snapshot_dir(kiro_output_dir)
    changed = new_files_since(before, after)

    urls = []
    if cloudfront_base_url and changed:
        for file_path in sorted(changed):
            url = build_url(file_path, kiro_output_dir, cloudfront_base_url, s3_prefix)
            if url:
                urls.append((Path(file_path).name, url))

    return output, urls


# ---------------------------------------------------------------------------
# Main loop
# ---------------------------------------------------------------------------

def main():
    api_key, chat_id, region, kiro_output_dir, cloudfront_base_url, s3_prefix = get_config()

    # Ensure output directory exists and update Kiro's steering file
    ensure_output_dir(kiro_output_dir)
    generate_kiro_context(kiro_output_dir, cloudfront_base_url, s3_prefix)

    bedrock = boto3.client('bedrock-runtime', region_name=region)
    offset = 0
    mode = "chat"
    awaiting_model = False

    # Kiro CLI slash commands that should be passed through
    kiro_commands = {
        "/context show", "/context clear", "/agent list",
        "/save", "/load", "/tools", "/prompts list", "/prompts get",
        "/prompts create", "/hooks", "/usage", "/mcp", "/tangents"
    }

    # Available models
    models = [
        ("auto", "1.00x credits", "Models chosen by task for optimal usage and consistent q.."),
        ("claude-opus-4.6", "2.20x credits", "Experimental preview of Claude Opus 4.6"),
        ("claude-opus-4.6-1m", "2.20x credits", "[Internal] Experimental preview of Claude Opus 4.6 1M co.."),
        ("claude-sonnet-4.6", "1.30x credits", "Experimental preview of the latest Claude Sonnet model"),
        ("claude-sonnet-4.6-1m", "1.30x credits", "[Internal] Experimental preview of Claude Sonnet 4.6 1M .."),
        ("claude-opus-4.5", "2.20x credits", "The Claude Opus 4.5 model"),
        ("claude-sonnet-4.5", "1.30x credits", "The Claude Sonnet 4.5 model"),
        ("claude-sonnet-4.5-1m", "1.30x credits", "[Internal] Experimental preview of Claude Sonnet 4.5 1M .."),
        ("claude-sonnet-4", "1.30x credits", "Hybrid reasoning and coding for regular use"),
        ("claude-haiku-4.5", "0.40x credits", "The latest Claude Haiku model"),
        ("deepseek-3.2", "0.25x credits", "Experimental preview of DeepSeek V3.2"),
        ("kimi-k2.5", "0.25x credits", "[Internal] Experimental preview of Kimi K2.5"),
        ("minimax-m2.1", "0.15x credits", "Experimental preview of MiniMax M2.1"),
        ("glm-4.7", "0.15x credits", "[Internal] Experimental preview of GLM 4.7"),
        ("glm-4.7-flash", "0.05x credits", "[Internal] Experimental preview of GLM 4.7 Flash"),
        ("qwen3-coder-next", "0.05x credits", "Experimental preview of Qwen3 Coder Next"),
        ("agi-nova-beta-1m", "0.01x credits", "[Internal] AGI Nova SWE Beta"),
        ("qwen3-coder-480b", "0.01x credits", "[Internal] Experimental preview of the Qwen3 model"),
    ]
    model_names = {m[0] for m in models}

    print(f"Bot started. Monitoring chat {chat_id}")

    while True:
        try:
            response = requests.get(
                f"https://api.telegram.org/bot{api_key}/getUpdates",
                params={"offset": offset, "timeout": 30},
                timeout=35
            )
            data = response.json()

            if data.get("ok") and data.get("result"):
                for update in data["result"]:
                    offset = update["update_id"] + 1

                    if "message" in update and "text" in update["message"]:
                        user_text = update["message"]["text"]
                        print(f"Received: {user_text}")

                        # Handle model selection if awaiting
                        if awaiting_model:
                            if user_text in model_names:
                                reply, new_files = invoke_kiro(
                                    f"/model {user_text}",
                                    kiro_output_dir,
                                    cloudfront_base_url,
                                    s3_prefix,
                                )
                                send_message(api_key, chat_id, reply)
                                awaiting_model = False
                            else:
                                send_message(api_key, chat_id, f"Invalid model: {user_text}. Please select from the list.")
                            continue

                        # Check if it's a Kiro CLI command (exact match or starts with pattern)
                        is_kiro_cmd = any(user_text == cmd or user_text.startswith(cmd + " ") 
                                         for cmd in kiro_commands)

                        if user_text == "/chat":
                            mode = "chat"
                            reply = "Switched to chat mode (Bedrock)"
                            send_message(api_key, chat_id, reply)

                        elif user_text == "/code":
                            mode = "code"
                            reply = "Switched to code mode (Kiro CLI)"
                            send_message(api_key, chat_id, reply)

                        elif user_text == "/status":
                            reply = check_monitor_status()
                            send_message(api_key, chat_id, reply)

                        elif user_text == "/model":
                            lines = ["Select model (type to search):"]
                            for name, credits, desc in models:
                                lines.append(f"  {name:<23} {credits:<18} {desc}")
                            send_message(api_key, chat_id, "\n".join(lines))
                            awaiting_model = True

                        elif user_text == "/help":
                            reply = (
                                "Available commands:\n"
                                "/chat - Switch to Bedrock chat mode\n"
                                "/code - Switch to Kiro CLI mode\n"
                                "/status - Check folder monitor status\n"
                                "/help - Show this help message\n\n"
                                "Kiro CLI commands (work in code mode):\n"
                                "/context show, /context clear\n"
                                "/model, /agent list\n"
                                "/save, /load\n"
                                "/tools, /prompts list, /prompts get, /prompts create\n"
                                "/hooks, /usage, /mcp, /tangents"
                            )
                            send_message(api_key, chat_id, reply)

                        elif is_kiro_cmd:
                            # Pass Kiro commands directly to Kiro CLI
                            reply, new_files = invoke_kiro(
                                user_text,
                                kiro_output_dir,
                                cloudfront_base_url,
                                s3_prefix,
                            )
                            send_message(api_key, chat_id, reply)

                            if new_files:
                                lines = ["Files created by Kiro:"]
                                for filename, url in new_files:
                                    lines.append(f"  {filename}: {url}")
                                send_message(api_key, chat_id, "\n".join(lines))

                        else:
                            if mode == "chat":
                                reply = invoke_bedrock(bedrock, user_text)
                                send_message(api_key, chat_id, reply)
                            else:
                                reply, new_files = invoke_kiro(
                                    user_text,
                                    kiro_output_dir,
                                    cloudfront_base_url,
                                    s3_prefix,
                                )
                                send_message(api_key, chat_id, reply)

                                if new_files:
                                    lines = ["Files created by Kiro:"]
                                    for filename, url in new_files:
                                        lines.append(f"  {filename}: {url}")
                                    send_message(api_key, chat_id, "\n".join(lines))

                        print(f"Sent reply ({mode} mode)")

        except Exception as e:
            print(f"Error: {e}")
            time.sleep(5)


if __name__ == "__main__":
    main()
